sonar.projectKey=axiom_engine_fabulous_samurai
sonar.projectName=AXIOM Zenith Engine
sonar.organization=fabulous-samurai
sonar.sources=src,include,core
sonar.tests=tests
sonar.language=cpp
sonar.cpp.file.suffixes=.cpp,.h,.hpp,.cc,.hh
sonar.cpp.std=c++23
sonar.python.version=3.12
sonar.sourceEncoding=UTF-8

# Coverage
sonar.python.coverage.reportPaths=coverage.xml
sonar.cfamily.build-wrapper-output=build_wrapper_output_directory
sonar.cfamily.gcov.reportsPath=.
sonar.cfamily.llvm-cov.reportPath=coverage.json
sonar.exclusions=build/**,extern/**,_deps/**
