sonar.projectKey=axiom_engine_fabulous_samurai
sonar.projectName=AXIOM Zenith Engine
sonar.organization=fabulous-samurai
sonar.sources=src,include,core
sonar.tests=tests
sonar.language=cpp
sonar.cpp.file.suffixes=.cpp,.h,.hpp,.cc,.hh
sonar.cpp.std=c++23
sonar.python.version=3.11
sonar.sourceEncoding=UTF-8
sonar.exclusions=build/**,extern/**,_deps/**
